### ISSUE TITLE
メッセージの整形場所について

### ISSUE THREAD

**Issue by aoba-s** [rkclhack/hackathon-tb-B#21]
# 問題提起
Chat.vueファイル、registerSocketEvent内のenterEvent, exitEvent, publishEventを受け取った時に行う処理やその他の箇所で

「文章の整形処理」
例:
```
`${ userName.value }さんが退室しました`
```

「chatListへdataを加える処理」
例:
```
chatList.unshift(data)
```

を実装しているが、これは適切ではないと考える。

onReceiveEnter, onReceiveExit, onReceivePublishが用意されているため「文章の整形処理」「chatListへdataを加える処理」はそちらで行うべきではないだろうか。

# 提案
そのため、下記のことを実施したい。

- registerSocketEvent内のenterEvent, exitEvent, publishEventを受け取った時に行う処理内でchatListへ値の追加を行わない。

- その代わり、その処理内でonReceiveEnter, onReceiveExit, onReceivePublishのいずれかにdataを渡す。

- onReceiveEnter, onReceiveExit, onReceivePublish内にて、「文章の整形処理」「chatListへdataを加える処理」を行う。

**Comment by aoba-s** [comment]
@pontabi @xxsatoxx @teruyuki-otani @Zanji05 
なので、皆が今日担当してくれた場所を上記の形式に修正して欲しいです！

修正できたらここにコメントしてほしい！

**Comment by pontabi** [comment]
`publishEvent` に関して、「chatListへdataを加える処理」は`onRecievePublish`でできているから、文章の整形処理だけ移動すれば良さそう
`enterEvent`と`exitEvent`はどちらも「文章の整形処理」「chatListへdataを加える処理」のどちらも移動させる必要ある。

自分は、exitEventを修正しておきます。

**Comment by pontabi** [comment]
exitEvent修正完了しました。

**Comment by pontabi** [comment]
他の２つ修正していないと思うので、修正時するとき、引数名を中身がわかるように命名してください。
現状デフォルトの`data`のままなので、引数名変えた方が良いかと思いました。
例えば、入室処理の方なら`enteredUserName`とか。

**Comment by teruyuki-otani** [comment]
publishEventも修正しました！

**Comment by pontabi** [comment]
@aoba-s 
Lineでも伝えたけど、整形場所は`displayedContents`のcomputedプロパティで管理するように変更したよ！
入室処理は手つけてないから、今正しく、動作してない

新しく作った`addChat`メソッド使ってchatListにデータ追加してくれるだけで勝手に`Aさんが退出しました`みたいに表示されるようになってるよー

**Comment by aoba-s** [comment]
完了しました〜！Closeするね
