### ISSUE TITLE
メッセージ投稿時、投稿者でなくログインユーザー名がラベルされている

### ISSUE THREAD

**Issue by pontabi** [rkclhack/hackathon-tb-B#22]
下記のように、AAAさんが投稿したメッセージがXXXさんのウィンドウでXXXさんが投稿したかのように表示されている。逆も同様。

実装したのが大谷さんなので、修正お願いします！来週のオンライン集会の時でも構いません

修正難しいようだったら相談してね:)

<img width="1439" alt="Screen Shot 2023-08-23 at 2 28 57" src="https://github.com/rkclhack/hackathon-tb-B/assets/51449117/c8d529ae-ac56-40ce-9d4e-0f5e1a43ebc7">

**Comment by xxsatoxx** [comment]
@teruyuki-otani 
メモ担の比重が少なそうなので、そこは今日中に私がやります。
なので、あおばさんが指摘した箇所の修正お願いします！
