### ISSUE TITLE
一度投稿したコメントを取り消せるようにしたい

### ISSUE THREAD

**Issue by aoba-s** [rkclhack/hackathon-tb-B#3]

**Comment by pontabi** [comment]
### chatList配列のidに関して
今後は、chatListをデータベースで管理する方針ということなので、現段階では仮のidをDateオブジェクトで定義します
```js
// chatList配列のデータモデル
const id = new Date().valueOf();
chatList.push({
  id: id
  content: "new content"
})
```

**Comment by pontabi** [comment]
ここでchatListの各値を ”実際に出力されるテキスト" からオブジェクトに変更してしまうと、みんなが実装してくれた他のコード(入退室機能や投稿機能）も変更する必要が出てくるので、相談したいです。次回のMeetingまでこのissueはとりあえず放置します。

**Comment by pontabi** [comment]
既にメンバーの了承を経て、オブジェクト型に変更できていたので、実装しました。若干バグかもしれない挙動が残っているので、別のissueを立てておきました。(#24)
